name: KKComboSkills
version: '1.0-SNAPSHOT'
main: com.kevinkwok.kkcomboskills.KKComboSkills
api-version: 1.12
commands:
  kkcskill:
    description: "Hello World"
    permission: KKComboSkills.admin
    aliases: kkcs
depend:
  - MythicMobs